### ISSUE TITLE
Sticker wear

### ISSUE THREAD

**Issue by sFireFrog** [csgofloat/inspect#108]
Sticker wear is now always 0.Did steam change something?

**Comment by Step7750** [comment]
Please give an example of an item that has obvious sticker wear in-game but shows up at 0.00 in the API.

**Comment by Step7750** [comment]
This is because we have very aggressive caching (kind of necessary for the prod API since we get 100 million+ requests per day). If we want to have sufficient speed (Valve's GC _is slower than our internal caches_) for the majority of requests, this is necessary.

So, this is a known tradeoff between performance and freshness -- notably Valve is _kind enough_ to not change the inspect URL at all when a sticker is scratched.

Once a sticker is fully scratched, the URL changes and will cache bust on our end.

**Comment by wangxingzhen** [comment]
> This is because we have very aggressive caching (kind of necessary for the prod API since we get 100 million+ requests per day). If we want to have sufficient speed (Valve's GC _is slower than our internal caches_) for the majority of requests, this is necessary.
> 
> So, this is a known tradeoff between performance and freshness -- notably Valve is _kind enough_ to not change the inspect URL at all when a sticker is scratched.
> 
> Once a sticker is fully scratched, the URL changes and will cache bust on our end.

Whether it is possible to add a flag parameter that indicates whether to use caching by default or to call Valve directly

**Comment by wangxingzhen** [comment]
> > This is because we have very aggressive caching (kind of necessary for the prod API since we get 100 million+ requests per day). If we want to have sufficient speed (Valve's GC _is slower than our internal caches_) for the majority of requests, this is necessary.
> > So, this is a known tradeoff between performance and freshness -- notably Valve is _kind enough_ to not change the inspect URL at all when a sticker is scratched.
> > Once a sticker is fully scratched, the URL changes and will cache bust on our end.
> 
> Whether it is possible to add a flag parameter that indicates whether to use caching by default or to call Valve directly

Or, if it has a sticker, don't cache it and just call Valve every time
