### ISSUE TITLE
Issue with request on csgo float api.

### ISSUE THREAD

**Issue by DJTaDJuk** [csgofloat/inspect#144]
i've made request on csgo float api using this link [https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20M4313928510476695418A29828853911D7061855787463663621](url)
but api gave me this:
![image](https://user-images.githubusercontent.com/114240459/234851098-de00d85a-764e-4dc5-b7a9-9c420ef08f1a.png)
What i did wrong?

**Comment by RevolveStrm** [comment]
The server could not process your request because your client sent GET request with headers which didn't contain or contained wrong "Origin" header. That's why you've got returned "Invalid Origin" error. I guess they changed "Origin" header rule on the server. So, we just have to wait for an official answer.

**Comment by downtowniwe1** [comment]
do u send this request from extension?

**Comment by DJTaDJuk** [comment]
no, just in browser

**Comment by Step7750** [comment]
This is expected, we've had to restrict access to the API due to Valve rate limits.
